#!/usr/bin/env python3

"""
A turnipripperdb has a config file which specifies the database
It defaults to .turnipripperdb. See config.py
"""

#a Imports
from libturnipripper.config import Config
from libturnipripper.toplevel import ToplevelCommand, ToplevelArgs
from pathlib import Path
import argparse
import sys
import traceback

import typing
from typing import Iterable, Optional, ClassVar, TypeVar, Type, Union, List, Dict, Tuple, Set, Any, cast

#a Main
def main() -> None:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter
    )

    cmd = ToplevelCommand(parser)
    cmd.parse_args()

    config_files = [Path("~/.turnipripperdb"),
                    Path("./.turnipripperdb"),
    ]
    if cmd.args.config_file: config_files.append(Path(cmd.args.config_file))
    config = Config()
    config.read_config_files(config_files)

    try:
        cmd.invoke(config)
    except Exception as e:
        if cmd.args.debug_test("any"):
            traceback.print_exc()
            pass
        else:
            print(e)
            pass
        sys.exit(4)
    pass

if __name__ == "__main__":
    main()
